// HelloWorld.idl : IDL source for HelloWorld
//

// This file will be processed by the MIDL tool to
// produce the type library (HelloWorld.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(F7E6D51E-3208-490C-B1E3-B857C0C0DEBA),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IHelloWorldBHO : IDispatch{
};
[
	uuid(02B23F26-B882-4007-9582-3290EAD33FD1),
	version(1.0),
]
library HelloWorldLib
{
	importlib("stdole2.tlb");
	[
		uuid(3B637A53-5B8C-4683-AC68-24D2565FC4AB)		
	]
	coclass HelloWorldBHO
	{
		[default] interface IHelloWorldBHO;
	};
};

